---
# tasks file for update_system
- name: Set Timezone
  timezone:
    name: "{{ time_zone }}"

- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: Update hosts
  lineinfile:
    path: /etc/hosts
    search_string: '127.0.0.1 myvm.local'
    line: 127.0.0.1 myvm.local
    state: present

