---
# tasks file for install_app
- name: Webapp directory creation
  file:
    path: "/var/www/app"
    state: directory
  tags: [ app ]

- name: Install application
  git:
    repo: "{{ repo_url }}"
    dest: /var/www/app/
    version: "{{ repo_branch }}"

 
- name: Set ownership
  file:
    path: "/var/www/app"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ app ]
